export const dynamic = 'force-dynamic';

import { apiError, apiOk } from '@/lib/api/error';
import { gh } from '@/lib/github/client';
import { triggerWebhook } from '@/lib/webhooks/send';
import { createAdminClient } from '@/lib/supabase/admin';
import { requireAuthContext } from '@/lib/security/auth-context';
import { hasTenantOrUserAccess } from '@/lib/security/ownership';
import { isInternalRequest } from '@/lib/security/internal-auth';

function parseGitHubRepo(url: string) {
    const cleaned = url.replace('https://github.com/', '').replace(/^\/+/, '').replace(/\/+$/, '');
    const [owner, repo] = cleaned.split('/');
    return { owner, repo };
}

export async function POST(req: Request) {
    // High-risk endpoint: disabled unless explicitly enabled, and requires internal auth.
    if (process.env.ENABLE_GITHUB_PR_WRITE !== 'true') {
        return apiError('Not found', 404);
    }

    if (!isInternalRequest(req.headers)) {
        return apiError('Forbidden', 403);
    }

    const auth = await requireAuthContext();
    if (!auth.ok) return auth.response;

    if (auth.ctx.tenantId !== auth.ctx.user.id && auth.ctx.role !== 'admin') return apiError('Forbidden', 403);

    const supabase = createAdminClient();

    try {
        const { patch_id, title, body: prBody } = await req.json();
        if (!patch_id) return apiError('patch_id is required', 400);

        // 1. Get patch from DB
        const { data: patch, error: patchErr } = await supabase
            .from('code_patches')
            .select('*, repositories(*)')
            .eq('id', patch_id)
            .single();

        if (patchErr || !patch) return apiError('Patch not found', 404);
        if (!hasTenantOrUserAccess(patch, { tenantId: auth.ctx.tenantId, userId: auth.ctx.user.id })) return apiError('Forbidden', 403);

        const repo = patch.repositories;
        if (!repo) return apiError('Not found', 404);
        if (!hasTenantOrUserAccess(repo, { tenantId: auth.ctx.tenantId, userId: auth.ctx.user.id })) return apiError('Forbidden', 403);
        const { owner, repo: repoName } = parseGitHubRepo(repo.repo_url);
        const branchName = `councilia/patch-${Math.random().toString(36).substring(7)}`;

        // 2. Create Branch
        const masterRef = await gh(`/repos/${owner}/${repoName}/git/ref/heads/master`);
        const sha = masterRef.object.sha;

        await gh(`/repos/${owner}/${repoName}/git/refs`, {
            method: 'POST',
            body: JSON.stringify({
                ref: `refs/heads/${branchName}`,
                sha
            })
        });

        // 3. Fetch current file content to get base SHA for commit
        const fileData = await gh(`/repos/${owner}/${repoName}/contents/${patch.file_path}`);

        // 4. Apply Patch (Simplificado para o MVP v2)
        const newContent = Buffer.from(Buffer.from(fileData.content, 'base64').toString('utf8') + `\n\n// CouncilIA: Applied Patch ${patch_id}`).toString('base64');

        await gh(`/repos/${owner}/${repoName}/contents/${patch.file_path}`, {
            method: 'PUT',
            body: JSON.stringify({
                message: `CouncilIA: ${title}`,
                content: newContent,
                sha: fileData.sha,
                branch: branchName
            })
        });

        // 5. Open PR
        const pr = await gh(`/repos/${owner}/${repoName}/pulls`, {
            method: 'POST',
            body: JSON.stringify({
                title: title || 'CouncilIA Contribution',
                body: prBody || 'This PR was automatically generated by CouncilIA based on code consensus.',
                head: branchName,
                base: 'master'
            })
        });

        // Update status
        await supabase.from('code_patches').update({
            status: 'applied'
        }).eq('id', patch_id);

        // Webhook
        await triggerWebhook({
            tenant_id: patch.tenant_id,
            event: 'patch.applied',
            payload: { patch_id: patch.id, pr_url: pr.html_url, branch: branchName }
        });

        return apiOk({ pr_url: pr.html_url, branch: branchName });

    } catch (error: any) {
        console.error('PR Error:', error);
        return apiError(error.message, 500);
    }
}
